appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: h5AmFhbqnaYOIJbQGiTpFOKBqcW29Qgw8fp/+pjQbSe87x2Q9FBUKukqIAcFEF/gJm0dKyxerCMUy/5LaQwoV5hv6Ta10oRnvNanuv7UsTOW3rR/6cEdxO0WN4q2R1/AClGNTpK3NTDTVtd8muxEmnKyA0SxQi/1mP4v9tQIi2ZszkSszjuwYor3i8rTpdlpel3GWrM3CUR3ECZgVXRGUrrPKTvtNkrrxfKWMscvoOvYtqy01QKjdKHdRZdG93JNBjiAsqW0a+hDstNnFep/80ET7ebdSkwIzmYChlaQu86tpjRHX0e3X1jkG/Xe462CeNXXzRJL0YiT+OeEAfxeJabPi5KJVybw9liOFSncHlmqHBck+HKQWgNI91/A5npGy3tTjDENdvOQziG2rM9tzNhkfaae7t/l6k36j+vf+LTZ9G+uCyNvC7xlWwnwIaWecHuc1PP9dXaznsoUepFMJvfcq3Az2d2z0pywVZIfWjQctxOLIkqVA7zvEgEt3q5wLfLIsWaktbUFu8D/ABaVxc2b8ZSFVoIODOfcZXs20NK5nW9Uyt8+FO5DGeWRYkPGR5ZEQ8SfL+28bS4W/Z0MbsB3kV0iHGU8b8HrGPKL/7mTzjAhKD1dZFCWK2aHhocBlk8Ns2lsyManCXmSoGVKEGt7rAy3497Gx4tSIn5wSvY=}
